# Project information 
site_name: Test-repository
site_description: Repositorio de test
site_author: Iker

# Repository
repo_name: TEST-repository
repo_url: https://github.com/iortizdeluzu/TEST-repository
~                                                              
