name: github-actions-learn
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env:
  SSH_KEY: ${{ secrets.EDR }}
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
            #user: iortiz
            #host: atlas-edr.sw.ehu.es
            #pass: ${{ secrets.EDR }}
            #- run: npm install -g bats
            #- run: npm install -g conda python3
            #- run: bats -v
        #- run: echo "Hello, world!" >> myfile.txt
      - run: git config --global user.name "iortizdeluzu"
      - run: git config --global user.mail "iker.ortiz@dipc.org"
        #- run: git add -A
        #- run: git commit -m "Auto updating"
        #- run: git fetch origin master
        #- run: git push origin main
      - run: sudo apt install sshpass
      - run: pip install virtualenv
      - run: virtualenv mypython
      - run: source mypython/bin/activate
      - run: conda init bash
      - run: python -m pip --version
      - run: pip install -r requirements.txt 
      - run: mkdocs build
      - run: echo $SSH_KEY
      # Hasta aqui corre
      - run: ssh-keygen -t rsa -N '' -f .ssh/id_rsa <<< y
      - run: ls .ssh
      - run: ls
      - run: which sshpass
        #- run: sshpass -p $pass scp README.md iortiz@atlas-edr.sw.ehu.es:/dipc/iortiz
      - run: git add -A
      - run: git commit -m "Auto updating"
      - run: git fetch origin master
      - run: git push origin main
      # Hasta aqui corre
      #- run: ssh-copy-id -i .ssh/id_rsa.pub iortiz@atlas-edr.sw.ehu.es
      #- run: |
      #       echo "$SSH_PRIVATE_KEY" > .ssh/id_rsa
      #       chmod 600 .ssh/id_rsa
      #       ssh-keyscan -H atlas-edr.sw.ehu.es >> .ssh/known_hosts
             #sshpass -p "joderCONdipc123$%&" ssh-copy-id -i .ssh/id_rsa.pub iortiz@$atlas-edr.sw.ehu.es
             #sshpass -p "$REMOTE_PASSWORD" ssh-copy-id -i .ssh/id_rsa.pub iortiz@$atlas-edr.sw.ehu.es
             #- run: rsync -r sites/ iortiz@atlas-edr.sw.ehu.es:/dipc/iortiz
  #env:
  #SSH_PRIVATE_KEY: ${{ secrets.EDR }}
  #REMOTE_HOST: atlas-edr.sw.ehu.es
  #REMOTE_USER: iortiz
  second-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
            #- name: Adding Known Hosts
      - name: get IP
        run: ip a
      - name: Deploy with rsync
        run: ls
          #run: rsync -avz README.md ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/iker/
      - name: cp test
        run: cp README.md README.test
      - name: key generation
        run:  ssh-keygen -t rsa -N '' -f .ssh/id_rsa <<< y
      - name: scp try
        env: 
          SSH_KEY: bibalabida
        run: scp README.test iker@158.227.108.220:/home/iker <<< $SSH_KEY
