name: actions
run-name: Deploy docs
on: [push]
env:
  SSH_PASS: ${{ secrets.SSHPASS }}
  REMOTE_SSH_USER: ${{ secrets.USERNAME }}
  REMOTE_IP: ${{ secrets.HOST }}
  REMOTE_DIR: ${{ secrets.SSH_DIR }}
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: |
          sudo apt install sshpass
          pip install virtualenv
          virtualenv mkdocs 
          source mkdocs/bin/activate
          pip install -r requirements.txt

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTATLAS }}
          username: ${{ secrets.USERNAMEATLAS }}
          password: ${{ secrets.SSHPASSATLAS }}
          script: ml av siesta >> README.md

      - name: Build documentation
        run: |
          ./mkdocs/bin/mkdocs build
      - name: ls documentation
        run: |
          ls
      - name: Setup SSH Key
        run: |
          ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa -q
     
      - name: Copy SSH public key to remote server
        run: |
          sshpass -p $SSH_PASS ssh-copy-id -o StrictHostKeyChecking=no $REMOTE_SSH_USER@$REMOTE_IP
      - name: Transfer directory via SCP
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./site $REMOTE_SSH_USER@$REMOTE_IP:$REMOTE_DIR
